# Nombre de la aplicación y puerto
spring.application.name=tienda-agropecuaria
server.port=8090

# Conexión a MySQL
spring.datasource.url=jdbc:mysql://localhost:3306/db_tienda_agropecuaria?useSSL=false&serverTimezone=UTC&allowPublicKeyRetrieval=true
spring.datasource.username=root
spring.datasource.password=123456789
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

# Configuración de JPA / Hibernate
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.database-platform=org.hibernate.dialect.MySQLDialect

# Actuator y Observabilidad (Métricas, Health Indicator y Prometheus)
management.endpoints.web.exposure.include=health,metrics,prometheus
management.endpoint.health.show-details=always
